**Tutorial 1**

In [ ]:
import torch

In [ ]:
x = torch.empty(1,2)
print(x)

tensor([[-3.9524e-33,  4.5226e-41]])


In [ ]:
x = torch.empty(2,2)
print(x)

tensor([[-3.9524e-33,  4.5226e-41],
        [-3.9524e-33,  4.5226e-41]])


In [ ]:
x = torch.rand(2,2)
print(x)

tensor([[0.4031, 0.0713],
        [0.2612, 0.1891]])


In [ ]:
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [ ]:
x = torch.ones(2,2, dtype=torch.float16)

print(x.size())
print(x.dtype)

torch.Size([2, 2])
torch.float16


In [ ]:
x = torch.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)


tensor([[0.8054, 0.2201],
        [0.8285, 0.5581]])
tensor([[0.8700, 0.1591],
        [0.9753, 0.2799]])


In [ ]:
z = x + y
print(z)

tensor([[1.6753, 0.3792],
        [1.8038, 0.8381]])


In [ ]:
z = torch.add(x,y)
print(z)

tensor([[1.6753, 0.3792],
        [1.8038, 0.8381]])


In [ ]:
y.add_(x)
print(y)

tensor([[1.6753, 0.3792],
        [1.8038, 0.8381]])


In [ ]:
z = x-y
print(z)

tensor([[-0.8700, -0.1591],
        [-0.9753, -0.2799]])


In [ ]:
z=torch.mul(x,y)
print(z)

tensor([[1.3492, 0.0835],
        [1.4945, 0.4678]])


In [ ]:
x = torch.rand(5,3)
print(x)
print(x[:,0])
print(x[1,:])

print(x[1,1])

print(x[1,1].item())

tensor([[0.4250, 0.5768, 0.5823],
        [0.4496, 0.5481, 0.4654],
        [0.5580, 0.6069, 0.6132],
        [0.0349, 0.4031, 0.0217],
        [0.7865, 0.7756, 0.2407]])
tensor([0.4250, 0.4496, 0.5580, 0.0349, 0.7865])
tensor([0.4496, 0.5481, 0.4654])
tensor(0.5481)
0.548124372959137


In [ ]:
import torch

x = torch.rand(4,4)
print(x)
y = x.view(-1,8)
print(y.size())

tensor([[0.6982, 0.2067, 0.7705, 0.6947],
        [0.0478, 0.7996, 0.9512, 0.7047],
        [0.2959, 0.3481, 0.5121, 0.5760],
        [0.5159, 0.9073, 0.7384, 0.1258]])
torch.Size([2, 8])


In [ ]:
import torch
import numpy as np

In [ ]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [ ]:
print(type(b))

<class 'numpy.ndarray'>


In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
a+=1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
x = torch.ones(5, requires_grad = True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


**Tutorial 2**

In [10]:
import torch

x = torch.randn(3,requires_grad=True)
print(x)

#y = x+2
#print(y)

#z=y*y*2
#z = y*y*2
#z = z.mean()
#print(z)
#z.backward()
#print(x.grad)

### x.requires_grad_(False)
### x.detach()
### with torch.no_grad():

#x.requires_grad_(False)
#print(x)

#y = x.detach()
#print(y)

with torch.no_grad():
    y = x+2
    print(y)

tensor([-0.9697,  0.2939, -0.1658], requires_grad=True)
tensor([1.0303, 2.2939, 1.8342])


In [18]:

import torch

weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
  model_output = (weights*3).sum()

  model_output.backward()

  print(weights.grad)
  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [20]:
### Backpropagation

import torch

x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0,requires_grad = True)

y_hat = w*x
loss = (y_hat - y)**2
print(loss)

loss.backward()
print(w.grad)


tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


**Gradient Descent with Autograd and Backpropagation**

In [3]:
import numpy as np

#f = w * x
#f = 2 * x

X = np.array([1,2,3,4], dtype = np.float32)
Y = np.array([2,4,6,8], dtype = np.float32)

w = 0.0

#model prediction
def forward(x):
  return w * x

#loss = MSE
def loss(y,y_predicted):
  return ((y_predicted-y)**2).mean()

#gradient
def gradient(x,y,y_predicted):
  return np.dot(2*x,y_predicted-y).mean()

def gradient(x,y,y_predicted):
  return np.dot(2*x,y_predicted-y).mean()

print(f'Prediction before training: f(5) = {forward(5):.3f}')

#Training
learning_rate = 0.01
n_iters = 20

for epoch in range(n_iters):
  #prediction = forward pass
  y_pred = forward(X)

  #loss
  l = loss(Y,y_pred)

  #gradients
  dw = gradient(X,Y,y_pred)

  #update weights
  w -= learning_rate * dw

  if epoch % 2 == 0:
    print(f'epoch {epoch+1}: w = {w:3f}, loss = {l:8f}')

print(f'Prediction after training: f(5) = {forward(5): .3f}')

#Training
learning_rate = 0.01
n_iters = 10

for epoch in range(n_iters):
  #prediction= forwand pass
  y_pred = forward(X)

  #loss
  l = loss(Y,y_pred)

  #gradients
  dw = gradient(X,Y,y_pred)

  #update weights
  w -= learning_rate * dw

  if epoch % 1 ==0:
    print(f'epoch {epoch + 1}: w = {w:.3f},loss = {l:.8f}')

print(f'Prediction after training: f(5) = {forward(5):.3f}')



Prediction before training: f(5) = 0.000
epoch 1: w = 1.200000, loss = 30.000000
epoch 3: w = 1.872000, loss = 0.768000
epoch 5: w = 1.979520, loss = 0.019661
epoch 7: w = 1.996723, loss = 0.000503
epoch 9: w = 1.999476, loss = 0.000013
epoch 11: w = 1.999916, loss = 0.000000
epoch 13: w = 1.999987, loss = 0.000000
epoch 15: w = 1.999998, loss = 0.000000
epoch 17: w = 2.000000, loss = 0.000000
epoch 19: w = 2.000000, loss = 0.000000
Prediction after training: f(5) =  10.000
epoch 1: w = 2.000,loss = 0.00000000
epoch 2: w = 2.000,loss = 0.00000000
epoch 3: w = 2.000,loss = 0.00000000
epoch 4: w = 2.000,loss = 0.00000000
epoch 5: w = 2.000,loss = 0.00000000
epoch 6: w = 2.000,loss = 0.00000000
epoch 7: w = 2.000,loss = 0.00000000
epoch 8: w = 2.000,loss = 0.00000000
epoch 9: w = 2.000,loss = 0.00000000
epoch 10: w = 2.000,loss = 0.00000000
Prediction after training: f(5) = 10.000


In [7]:
import torch

#f = w * x
#f = 2 * x

X = torch.tensor([1,2,3,4], dtype = torch.float32)
Y = torch.tensor([2,4,6,8], dtype = torch.float32)

w = torch.tensor(0.0, dtype = torch.float32, requires_grad= True)

#model prediction
def forward(x):
  return w * x

#loss = MSE
def loss(y,y_predicted):
  return ((y_predicted-y)**2).mean()


print(f'Prediction before training: f(5) = {forward(5):.3f}')

#Training
learning_rate = 0.01
n_iters = 100

for epoch in range(n_iters):
  #prediction = forward pass
  y_pred = forward(X)

  #loss
  l = loss(Y,y_pred)

  #gradients = backward pass
  l.backward()

  #update weights

  with torch.no_grad():
        w -= learning_rate * w.grad

  w.grad.zero_()

  if epoch % 10 == 0:
    print(f'epoch {epoch+1}: w = {w:3f}, loss = {l:8f}')

print(f'Prediction after training: f(5) = {forward(5): .3f}')


Prediction before training: f(5) = 0.000
epoch 1: w = 0.300000, loss = 30.000000
epoch 11: w = 1.665314, loss = 1.162786
epoch 21: w = 1.934109, loss = 0.045069
epoch 31: w = 1.987028, loss = 0.001747
epoch 41: w = 1.997446, loss = 0.000068
epoch 51: w = 1.999497, loss = 0.000003
epoch 61: w = 1.999901, loss = 0.000000
epoch 71: w = 1.999980, loss = 0.000000
epoch 81: w = 1.999996, loss = 0.000000
epoch 91: w = 1.999999, loss = 0.000000
Prediction after training: f(5) =  10.000


**Training pipeline:Model, Loss and Optimizer**

In [11]:
# 1. Design model(input, output size, forwand pass)
# 2. Construct loss and optimizer
# 3. Training loop
#    - forward pass: compute prediction
#    - backward pass: gradients
#     -update weights

import torch
import torch.nn as nn

X = torch.tensor([1,2,3,4], dtype = torch.float32)
Y = torch.tensor([2,4,6,8], dtype = torch.float32)

w = torch.tensor(0.0, dtype=torch.float32, requires_grad = True)

#model prediction
def forward(x):
  return w * x

print(f'Prediction before training: f(5) = {forward(5): .3f}')
#Training
learning_rate = 0.01
n_iters = 100

loss = nn.MSELoss()
optimizer = torch.optim.SGD([w], lr=learning_rate)


for epoch in range(n_iters):
  #prediction = forward pass
  y_pred = forward(X)

  #loss
  l = loss(Y,y_pred)

  #gradients = backward pass
  l.backward()

  #update weights

  optimizer.step()

  #zero gradients
  optimizer.zero_grad()

  if epoch % 10 == 0:
    print(f'epoch {epoch+1}: w = {w:3f}, loss = {l:8f}')

print(f'Prediction after training: f(5) = {forward(5): .3f}')


Prediction before training: f(5) =  0.000
epoch 1: w = 0.300000, loss = 30.000000
epoch 11: w = 1.665314, loss = 1.162786
epoch 21: w = 1.934109, loss = 0.045069
epoch 31: w = 1.987028, loss = 0.001747
epoch 41: w = 1.997446, loss = 0.000068
epoch 51: w = 1.999497, loss = 0.000003
epoch 61: w = 1.999901, loss = 0.000000
epoch 71: w = 1.999980, loss = 0.000000
epoch 81: w = 1.999996, loss = 0.000000
epoch 91: w = 1.999999, loss = 0.000000
Prediction after training: f(5) =  10.000


In [21]:

import torch
import torch.nn as nn

X = torch.tensor([[1],[2],[3],[4]], dtype = torch.float32)
Y = torch.tensor([[2],[4],[6],[8]], dtype = torch.float32)

X_test = torch.tensor([5], dtype = torch.float32)

n_samples, n_features = X.shape
print(n_samples, n_features)

input_size = n_features
output_size = n_features

model = nn.Linear(input_size, output_size)


print(f'Prediction before training: f(5) = {model(X_test).item(): .3f}')
#Training
learning_rate = 0.01
n_iters = 100

loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)


for epoch in range(n_iters):
  #prediction = forward pass
  y_pred = model(X)

  #loss
  l = loss(Y,y_pred)

  #gradients = backward pass
  l.backward()

  #update weights

  optimizer.step()

  #zero gradients
  optimizer.zero_grad()

  if epoch % 10 == 0:
    [w,b] = model.parameters()
    print(f'epoch {epoch+1}: w = {w[0][0].item():.3f}, loss = {l:8f}')

print(f'Prediction after training: f(5) = {model(X_test).item(): .3f}')


4 1
Prediction before training: f(5) =  0.534
epoch 1: w = 0.262, loss = 24.758614
epoch 11: w = 1.408, loss = 0.839227
epoch 21: w = 1.601, loss = 0.208813
epoch 31: w = 1.641, loss = 0.181612
epoch 41: w = 1.656, loss = 0.170652
epoch 51: w = 1.667, loss = 0.160709
epoch 61: w = 1.677, loss = 0.151355
epoch 71: w = 1.687, loss = 0.142545
epoch 81: w = 1.696, loss = 0.134248
epoch 91: w = 1.705, loss = 0.126434
Prediction after training: f(5) =  9.408
