<a href="https://colab.research.google.com/github/sumita-dangal/Calculator-JS/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tutorial 1**

In [41]:
import torch

In [42]:
x = torch.empty(1,2)
print(x)

tensor([[-3.9524e-33,  4.5226e-41]])


In [43]:
x = torch.empty(2,2)
print(x)

tensor([[-3.9524e-33,  4.5226e-41],
        [-3.9524e-33,  4.5226e-41]])


In [44]:
x = torch.rand(2,2)
print(x)

tensor([[0.4031, 0.0713],
        [0.2612, 0.1891]])


In [45]:
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [46]:
x = torch.ones(2,2, dtype=torch.float16)

print(x.size())
print(x.dtype)

torch.Size([2, 2])
torch.float16


In [47]:
x = torch.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


In [48]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)


tensor([[0.8054, 0.2201],
        [0.8285, 0.5581]])
tensor([[0.8700, 0.1591],
        [0.9753, 0.2799]])


In [49]:
z = x + y
print(z)

tensor([[1.6753, 0.3792],
        [1.8038, 0.8381]])


In [50]:
z = torch.add(x,y)
print(z)

tensor([[1.6753, 0.3792],
        [1.8038, 0.8381]])


In [51]:
y.add_(x)
print(y)

tensor([[1.6753, 0.3792],
        [1.8038, 0.8381]])


In [52]:
z = x-y
print(z)

tensor([[-0.8700, -0.1591],
        [-0.9753, -0.2799]])


In [53]:
z=torch.mul(x,y)
print(z)

tensor([[1.3492, 0.0835],
        [1.4945, 0.4678]])


In [54]:
x = torch.rand(5,3)
print(x)
print(x[:,0])
print(x[1,:])

print(x[1,1])

print(x[1,1].item())

tensor([[0.4250, 0.5768, 0.5823],
        [0.4496, 0.5481, 0.4654],
        [0.5580, 0.6069, 0.6132],
        [0.0349, 0.4031, 0.0217],
        [0.7865, 0.7756, 0.2407]])
tensor([0.4250, 0.4496, 0.5580, 0.0349, 0.7865])
tensor([0.4496, 0.5481, 0.4654])
tensor(0.5481)
0.548124372959137


In [55]:
import torch

x = torch.rand(4,4)
print(x)
y = x.view(-1,8)
print(y.size())

tensor([[0.6982, 0.2067, 0.7705, 0.6947],
        [0.0478, 0.7996, 0.9512, 0.7047],
        [0.2959, 0.3481, 0.5121, 0.5760],
        [0.5159, 0.9073, 0.7384, 0.1258]])
torch.Size([2, 8])


In [56]:
import torch
import numpy as np

In [57]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [58]:
print(type(b))

<class 'numpy.ndarray'>


In [59]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [60]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [61]:
a+=1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [62]:
x = torch.ones(5, requires_grad = True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


**Tutorial 2**

In [66]:
import torch

x = torch.randn(3,requires_grad=True)
print(x)

y = x+2
print(y)

z=y*y*2
z = y*y*2
z = z.mean()
print(z)

tensor([ 0.9449, -0.1378, -0.6691], requires_grad=True)
tensor([2.9449, 1.8622, 1.3309], grad_fn=<AddBackward0>)
tensor(9.2743, grad_fn=<MeanBackward0>)


In [67]:
z.backward()
print(x.grad)

tensor([3.9265, 2.4829, 1.7745])
